CYF-ITP | Emmanuel Siziba | module_user_focused_Data |Week1
CodeYourFuture/Module-Structuring-and-Testing-Data pull request #119
Opened 2024-11-11 14:46 UTC by EmmanuelSiziba

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://curriculum.codeyourfuture.io/guides/contributing/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-11-19 07:35 UTC, SallyMcGrath requested changes
Hi there @EmmanuelSiziba . I got a way through this but I'm going to take a break and say, please:

1. spellcheck your writing
2. put it in comments
3. then ask for another review.

Ta! Good start!

2024-11-19 07:35 UTC, SallyMcGrath commented on Sprint-1/exercises/decimal.js
> +CSSCounterStyleRule
what is happening here?

2024-12-04 10:10 UTC, EmmanuelSiziba commented on Sprint-1/errors/4.js
> +//error: on both of these variables the keyword is follliwing a numeric literal wich cannont happen in other words variable names cannot start with a Number.
It looks like my Grammarly wasn't installed properly I was able to install it and the spelling errors I had made.

2024-12-18 06:58 UTC, EmmanuelSiziba commented on Sprint-1/errors/3.js
> +Why the code wont Work, the code wont work becuase the was no console(log) to show our output.
You have to test it to see the output

2025-09-01 18:10 UTC, closed without merging