northwest |Rahwa Zeslus |module-structure-and-Testing-Data | WEEK3
CodeYourFuture/Module-Structuring-and-Testing-Data pull request #224
Opened 2024-12-09 19:45 UTC by RahwaZeslusHaile

northwest |Rahwa Zeslus |module-structure-and-Testing-Data | WEEK3

For example,

NW4 | Carol Owen | HTML-CSS-Module | Week1

2024-12-10 20:23 UTC, codrex requested changes

2024-12-14 23:54 UTC, RahwaZeslusHaile commented
thank you for your constructive reviews, I updated with the corrected one .

2024-12-16 23:18 UTC, RahwaZeslusHaile commented
Please take a look when you have the chance and let me know if there are any improvements or issues you see. Thanks in advance

2024-12-19 23:49 UTC, cjyuan commented
@RahwaZeslusHaile I think you can tag the reviewer (like what I did here with your ID) to let the reviewer know you would like a follow-up review from the reviewer.

2025-01-02 18:51 UTC, cjyuan reviewed
The code is quite solid.
`card-validator.md` has a bug that needs fixing.

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/implement/is-valid-triangle.js
> +    }
If any of `a`, `b`, and `c` is less than or equal to zero, then the condition at line 43 will always be false.
Is there any need to further check if `a`, `b`, and `c` is less than or equal to zero at line 51?

I will not go into details why in some programming languages (but not JavaScript) we need also to ensure a, b, c are positives.

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/implement/rotate-char.js
> +        const rotatedCode = ((charCode - 97 + shift) % 26) + 97; // 'a' starts at ASCII 97
This approach is good. 
If `shift` were allowed to be negative so that `charCode - 97 + shift` can become a negative number, how would you modify your code to deal with negative `shift`?

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/revise/implement/card-validator.md
> +}
Have you fully tested this function? It missed checking something in the given `cardNumber`.

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/revise/implement/is-prime.js
> +        throw new Error('There is no negative prime number or zero as a prime number.');
How are these non-prime numbers (e.g., -100, 1, 0) any different from other non-prime numbers (e.g., 10, 15, 100)?

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/revise/implement/is-prime.js
> +    for (let index = 3; index <= Math.sqrt(number); index += 2) {
You can possibly improve the performance of the code in the following manner:
- Avoid calling `Math.sqrt(num)` repeatedly by assigning the value of `Math.sqrt(num)` to a variable once, and then refer to the variable in the condition of the loop.
  - Note: The condition is checked at the start of every iteration.

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/revise/implement/password-validator.test.js
> +        expect(isValidPassword('P1!', previousPasswords)).toBe(false);
The function could have also returned `false` because `P1!` does not contain any lowercase letter. How can we be 100% sure the function can correctly check passwords shorter than 5 characters?

2025-01-02 18:51 UTC, cjyuan commented on Sprint-3/revise/implement/repeat.js
> +    return str.repeat(count);
These statements could be greatly shorten if you know how `String.repeat()` works.

2025-01-04 22:24 UTC, RahwaZeslusHaile commented on Sprint-3/implement/get-angle-type.js
> +}
Yes I understand ,I didn't see that way. So what I have done in this new code is try to change the degrees to to an equivalent angle within the standard range of 
0 degree to 360 degree

2025-01-13 22:29 UTC, RahwaZeslusHaile commented on Sprint-3/implement/get-card-value.js
> +    }
1,getCardValue("010♠");  
!isNaN(rank) → true because "010" is a numeric string.
Number(rank) → 10 (leading zeros are ignored by Number()).
Number(rank) >= 2 && Number(rank) <= 10 → true.

2,getCardValue("02♠");  

!isNaN(rank) → true because "02" is a numeric string.
Number(rank) → 2 (leading zeros are ignored by Number()).
Number(rank) >= 2 && Number(rank) <= 10 → true.

2025-01-13 22:46 UTC, cjyuan commented on Sprint-3/implement/get-card-value.js
> +    }
At the end, do you want the function to recognise these card values?

2025-01-13 22:51 UTC, RahwaZeslusHaile commented on Sprint-3/implement/is-valid-triangle.js
> +    }
Thank you for your review! You're absolutely right in your observation. Since the check for whether any side is less than or equal to zero is already handled in the first condition (a <= 0 || b <= 0 || c <= 0) at line 43, the second check at line 51 is unnecessary.

This means the function can be simplified by removing that second check, making the logic more concise and clearer.

2025-01-21 16:27 UTC, RahwaZeslusHaile commented on Sprint-3/revise/implement/card-validator.md
> +}
Yes! You are right—it misses checking the card in a lot of ways. I updated the code to have more comprehensive validations, including checks for:

1,Ensuring the card contains only numeric characters.
2,Verifying the card number length is exactly 16 digits.
3,Confirming the card has at least two unique digits.
4,Applying the Luhn algorithm for number validation.
5,Validating that the last digit (check digit) is even

2025-01-21 16:43 UTC, RahwaZeslusHaile commented on Sprint-3/revise/implement/is-prime.js
> +        throw new Error('There is no negative prime number or zero as a prime number.');
you’re absolutely right that treating numbers less than or equal to 1 differently by throwing an error while returning false for other non-prime numbers (e.g., 10, 15) introduces unnecessary complexity. Thank you

2025-01-21 16:44 UTC, RahwaZeslusHaile commented on Sprint-3/revise/implement/is-prime.js
> +    for (let index = 3; index <= Math.sqrt(number); index += 2) {
Thank you for pointing out the potential improvement in performance by avoiding the repeated calculation of Math.sqrt(number) in the loop condition.

2025-01-21 17:41 UTC, RahwaZeslusHaile commented on Sprint-3/revise/implement/password-validator.test.js
> +        expect(isValidPassword('P1!', previousPasswords)).toBe(false);
Thank you for pointing out that ,I tried to include requirement to make the password valid(the lower case letter, uppercase letter, a number,and one-alphanumeric symbol) unless the length is less than 5. So the test only checks that the length is less than five and returns false.

2025-01-21 18:23 UTC, RahwaZeslusHaile commented
I’ve made corrections to improve the overall functionality, readability, and efficiency of the code. 

Can you please review the updates and provide feedback?

2025-04-28 21:06 UTC, closed without merging